app.storage.bucket=${GCS_BUCKET}
google.cloud.project-id=${GCP_PROJECT_ID}

allowed.origins=${ALLOWED_ORIGINS}

spring.cloud.gcp.firestore.enabled=false
spring.cloud.gcp.storage.enabled=false
spring.cloud.gcp.core.enabled=false
