spring.application.name=cnse-qrcode

server.address=0.0.0.0
server.port=${PORT}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

minio.url=${MINIO_URL}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
app.storage.bucket=${QR_STORAGE_BUCKET}

firestore.emulator-host=${FIRESTORE_EMULATOR_HOST}
firestore.project-id=${FIRESTORE_PROJECT_ID}

allowed.origins=${ALLOWED_ORIGINS}

firebase.credentials=${FIREBASE_CREDENTIALS}
